In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
data= pd.read_csv(r"C:\Users\rafam\OneDrive\Documentos\GitHub\Proyecto Machine Learning\fraudTrain.csv")
df= pd.DataFrame(data)
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [35]:
df_delinq_usstates= pd.read_csv(r"C:\Users\rafam\OneDrive\Documentos\GitHub\ENTREGA_FRAUDE\deliq_by_state.csv")
df_delinq_usstates

,state,credit_card_delinq_rate_90_days,Per_capita_creditcard_debt,Credit_card_debt_as_share_non-mortgage debt,Av_cred_score
0,NV,0.1200,3350,0.209,701
1,FL,0.1066,3450,0.196,706
2,AR,0.1023,2380,0.153,694
3,TX,0.0943,3190,0.175,692
4,AZ,0.0940,3060,0.185,710
5,OK,0.0916,2530,0.164,692
6,CA,0.0907,3330,0.215,721
7,NM,0.0907,2540,0.177,699
8,NY,0.0894,3520,0.213,722
9,GA,0.0891,3210,0.163,693
10,MS,0.0877,2150,0.123,681
11,SC,0.0863,2810,0.160,693
12,LA,0.0860,2520,0.142,689
13,AL,0.0853,2370,0.144,691
14,DE,0.0838,3180,0.183,714
15,WV,0.0830,2250,0.153,699
16,NC,0.0815,2880,0.168,707
17,TN,0.0783,2540,0.156,701
18,PA,0.0781,2960,0.172,723
19,KY,0.0776,2290,0.154,702
20,MO,0.0767,2570,0.168,711
21,MD,0.0756,3690,0.187,716
22,AK,0.0753,4070,0.246,717
23,RI,0.0749,3090,0.192,723
24,WY,0.0741,2930,0.200,722
25,NJ,0.0738,3700,0.212,725
26,MA,0.0728,3310,0.196,732
27,HI,0.0727,3750,0.223,732
28,OH,0.0718,2620,0.159,715
29,CT,0.0710,3610,0.214,728
30,IN,0.0708,2430,0.158,712
31,IL,0.0704,3060,0.192,719
32,KS,0.0682,2700,0.183,721
33,OR,0.0679,2800,0.179,731
34,MI,0.0676,2600,0.167,719
35,NE,0.0672,2730,0.183,731
36,ID,0.0671,2620,0.158,725
37,MT,0.0667,2840,0.184,730
38,IA,0.0665,2450,0.162,729
39,VA,0.0660,3560,0.201,721
40,CO,0.0657,3480,0.193,728
41,NH,0.0656,3240,0.174,734
42,SD,0.0644,2640,0.159,733
43,ME,0.0636,2600,0.159,727
44,ND,0.0603,2990,0.174,733
45,VT,0.0603,2830,0.166,736
46,MN,0.0578,3000,0.184,742
47,WA,0.0577,3250,0.208,734
48,UT,0.0566,2870,0.175,727
49,WI,0.0534,2510,0.177,735

In [36]:
merged_df1= pd.merge(df, df_delinq_usstates, on= 'state', how= 'inner')
merged_df1

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,credit_card_delinq_rate_90_days,Per_capita_creditcard_debt,Credit_card_debt_as_share_non-mortgage debt,Av_cred_score
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,0.0815,2880,0.168,707
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,0.0577,3250,0.208,734
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,0.0671,2620,0.158,725
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,0.0667,2840,0.184,730
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,0.0660,3560,0.201,721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293057,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,0.0566,2870,0.175,727
1293058,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,0.0756,3690,0.187,716
1293059,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,0.0907,2540,0.177,699
1293060,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,0.0644,2640,0.159,733
1293061,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,0.0667,2840,0.184,730